# THIS FILE IS JUST FOR INFORMATION. PUT SETTINGS INTO config.yaml INSTEAD!
host:                  'localhost'
port:                  6667
websockethost:         'localhost'
websocketport:         3141
logfile:               'tmoohi_%Y_%m_%d.log'
logfile-logfilter:     
-   level__ge:         20
    type:              'event'
console-logfilter:     
-   level__ge:         0
    type:              'event'
channels-per-connection: 10
messages-per-30:       15
connections-per-10:    45
capacity-target:       0.75
ratelimit-commands:    true